In [1]:
def fgh(vec):
    x = vec[0]
    y = vec[1]
    z = vec[2]
    f = x**2 + 2*(y**2) + 4*(z**2) - 7
    g = 2*(x**2) + y**3 + 6*z -10
    h = x*y*z +1
    return [f,g,h]

In [2]:
def jacobian(vec):
    x = vec[0]
    y = vec[1]
    z = vec[2]
    
    fx = 2*x
    fy = 4*y
    fz = 8*z
    gx = 4*x
    gy = 3*(y**2)
    gz = 12*z
    hx = y*z
    hy = x*z
    hz = x*y
    
    A = fx*(gy*hz-gz*hy)-fy*(gx*hz-gz*hx)+fz*(gx*hy-gy*hx)
    J = [[fx, fy, fz],
        [gx, gy, gz],
        [hx, hy, hz]]

    J = np.array(J)
    J = np.divide(J, A)
    return J

In [3]:
import numpy as np

np.set_printoptions(precision=10, suppress=True)

vec = [1., -1., 1.2]
rlt_err = 10**(-8)

In [4]:
X_old = np.array(vec)
cons = np.matmul(jacobian(vec),fgh(vec)) 
X_new = X_old - cons
x_abs = abs(X_new-X_old)
min_abs = x_abs.min()

while x_abs.min() > rlt_err:
    X_old = X_new
    cons = np.matmul(jacobian(X_old),fgh(X_old)) 
    X_new = X_old - cons
    x_abs = abs(X_new-X_old)
    print(x_abs)

[0.0970951871 0.0000925135 0.0436597333]
[0.0991477015 0.010533242  0.0436608842]
[0.099760996  0.0186226183 0.0435569791]
[0.0987061166 0.0244860788 0.0433643353]
[0.0961322951 0.0285619154 0.043173516 ]
[0.0923662295 0.0312919876 0.0430838055]
[0.0877721375 0.0330524124 0.0431674243]
[0.0826788154 0.0341337708 0.0434598609]
[0.0773534957 0.0347483384 0.0439647352]
[0.0720001891 0.0350464192 0.0446635509]
[0.0667677347 0.0351326701 0.0455251742]
[0.0617601077 0.0350792927 0.0465131696]
[0.0570460102 0.0349357786 0.0475907841]
[0.0526669213 0.0347358252 0.0487239824]
[0.0486436168 0.0345021722 0.0498830525]
[0.0449814025 0.0342499759 0.0510432376]
[0.0416743086 0.0339891703 0.0521847456]
[0.0387084438 0.0337261232 0.0532923913]
[0.0360646558 0.0334647989 0.0543550474]
[0.0337206094 0.0332075707 0.0553650222]
[0.0316523759 0.0329557847 0.0563174382]
[0.0298356157 0.0327101436 0.0572096566]
[0.0282464259 0.0324709661 0.0580407693]
[0.02686192   0.0322383545 0.0588111675]
[0.0256605976 0.

[0.0233909657 0.001834339  0.0010774477]
[0.0234369994 0.0019007097 0.0011773026]
[0.0234830124 0.0019662371 0.0012779823]
[0.0235290066 0.0020309263 0.001379488 ]
[0.0235749838 0.0020947821 0.0014818211]
[0.0236209457 0.0021578093 0.0015849828]
[0.0236668944 0.0022200126 0.0016889745]
[0.0237128315 0.0022813969 0.0017937977]
[0.0237587592 0.0023419667 0.0018994539]
[0.0238046793 0.0024017267 0.0020059447]
[0.0238505937 0.0024606814 0.0021132717]
[0.0238965046 0.0025188353 0.0022214366]
[0.0239424139 0.002576193  0.0023304413]
[0.0239883238 0.0026327588 0.0024402876]
[0.0240342362 0.0026885371 0.0025509775]
[0.0240801534 0.0027435322 0.0026625129]
[0.0241260774 0.0027977484 0.002774896 ]
[0.0241720104 0.0028511899 0.002888129 ]
[0.0242179548 0.0029038609 0.003002214 ]
[0.0242639126 0.0029557654 0.0031171535]
[0.0243098862 0.0030069076 0.0032329498]
[0.0243558778 0.0030572915 0.0033496054]
[0.0244018898 0.003106921  0.003467123 ]
[0.0244479246 0.0031558001 0.0035855053]
[0.0244939844 0.

[0.0565933522 0.0365299171 0.0130058429]
[0.0575506122 0.036105808  0.013551421 ]
[0.0585180459 0.0356531361 0.0140870008]
[0.0594948403 0.0351722543 0.0146109026]
[0.0604801209 0.0346636207 0.0151214331]
[0.0614729529 0.034127801  0.0156168974]
[0.0624723432 0.0335654687 0.0160956113]
[0.0634772433 0.0329774059 0.0165559142]
[0.0644865519 0.032364502  0.0169961831]
[0.0654991195 0.031727752  0.017414846 ]
[0.0665137521 0.0310682535 0.0178103963]
[0.0675292167 0.0303872027 0.0181814067]
[0.0685442469 0.0296858894 0.0185265425]
[0.0695575488 0.0289656907 0.0188445749]
[0.0705678076 0.0282280641 0.0191343936]
[0.0715736947 0.0274745396 0.0193950178]
[0.072573875  0.0267067105 0.0196256064]
[0.0735670142 0.025926224  0.019825467 ]
[0.0745517867 0.025134771  0.019994063 ]
[0.0755268829 0.0243340755 0.0201310192]
[0.0764910174 0.0235258829 0.0202361256]
[0.0774429361 0.0227119496 0.0203093387]
[0.0783814234 0.0218940308 0.0203507823]
[0.0793053093 0.0210738702 0.0203607445]
[0.0802134758 0.

[0.0750385396 0.003809336  0.0000023362]
[0.0749959594 0.0038049722 0.0000023276]
[0.0749534755 0.0038006207 0.000002319 ]
[0.0749110876 0.0037962817 0.0000023104]
[0.0748687952 0.0037919549 0.0000023019]
[0.0748265982 0.0037876404 0.0000022935]
[0.0747844959 0.0037833382 0.0000022851]
[0.0747424882 0.0037790481 0.0000022768]
[0.0747005745 0.0037747701 0.0000022685]
[0.0746587547 0.0037705041 0.0000022602]
[0.0746170281 0.0037662502 0.000002252 ]
[0.0745753947 0.0037620081 0.0000022438]
[0.0745338538 0.003757778  0.0000022357]
[0.0744924053 0.0037535597 0.0000022276]
[0.0744510487 0.0037493532 0.0000022196]
[0.0744097837 0.0037451584 0.0000022116]
[0.0743686099 0.0037409752 0.0000022037]
[0.074327527  0.0037368037 0.0000021958]
[0.0742865346 0.0037326438 0.000002188 ]
[0.0742456324 0.0037284954 0.0000021802]
[0.07420482   0.0037243585 0.0000021724]
[0.0741640971 0.003720233  0.0000021647]
[0.0741234634 0.0037161188 0.000002157 ]
[0.0740829185 0.003712016  0.0000021494]
[0.0740424621 0.

[0.0643632746 0.0027952714 0.0000008766]
[0.0643402134 0.0027932538 0.0000008746]
[0.0643171853 0.0027912398 0.0000008726]
[0.0642941901 0.0027892295 0.0000008706]
[0.0642712278 0.0027872228 0.0000008687]
[0.0642482982 0.0027852197 0.0000008667]
[0.0642254014 0.0027832202 0.0000008648]
[0.0642025371 0.0027812242 0.0000008629]
[0.0641797054 0.0027792318 0.0000008609]
[0.0641569062 0.002777243  0.000000859 ]
[0.0641341394 0.0027752577 0.0000008571]
[0.0641114048 0.002773276  0.0000008552]
[0.0640887025 0.0027712978 0.0000008533]
[0.0640660323 0.0027693231 0.0000008513]
[0.0640433941 0.0027673519 0.0000008495]
[0.0640207879 0.0027653843 0.0000008476]
[0.0639982137 0.0027634201 0.0000008457]
[0.0639756712 0.0027614594 0.0000008438]
[0.0639531605 0.0027595021 0.0000008419]
[0.0639306815 0.0027575483 0.0000008401]
[0.063908234  0.002755598  0.0000008382]
[0.0638858181 0.0027536511 0.0000008364]
[0.0638634336 0.0027517076 0.0000008345]
[0.0638410804 0.0027497676 0.0000008327]
[0.0638187585 0.

[0.0565929405 0.00215736   0.0000003916]
[0.0565791588 0.002156303  0.000000391 ]
[0.0565653906 0.0021552473 0.0000003904]
[0.0565516357 0.0021541929 0.0000003899]
[0.0565378943 0.0021531398 0.0000003893]
[0.0565241662 0.002152088  0.0000003887]
[0.0565104515 0.0021510375 0.0000003881]
[0.0564967501 0.0021499883 0.0000003875]
[0.0564830619 0.0021489403 0.0000003869]
[0.0564693871 0.0021478936 0.0000003863]
[0.0564557254 0.0021468482 0.0000003858]
[0.0564420771 0.002145804  0.0000003852]
[0.0564284419 0.0021447611 0.0000003846]
[0.0564148199 0.0021437195 0.000000384 ]
[0.056401211  0.0021426791 0.0000003834]
[0.0563876153 0.00214164   0.0000003829]
[0.0563740327 0.0021406022 0.0000003823]
[0.0563604632 0.0021395656 0.0000003817]
[0.0563469067 0.0021385303 0.0000003812]
[0.0563333633 0.0021374962 0.0000003806]
[0.056319833  0.0021364633 0.00000038  ]
[0.0563063156 0.0021354318 0.0000003795]
[0.0562928112 0.0021344014 0.0000003789]
[0.0562793198 0.0021333723 0.0000003783]
[0.0562658413 0.

[0.0520646621 0.001824195  0.0000002335]
[0.0520547924 0.0018234997 0.0000002332]
[0.0520449301 0.0018228051 0.0000002329]
[0.0520350754 0.0018221112 0.0000002327]
[0.0520252281 0.0018214179 0.0000002324]
[0.0520153883 0.0018207253 0.0000002321]
[0.052005556  0.0018200333 0.0000002318]
[0.0519957311 0.001819342  0.0000002316]
[0.0519859136 0.0018186514 0.0000002313]
[0.0519761035 0.0018179614 0.000000231 ]
[0.0519663009 0.0018172721 0.0000002308]
[0.0519565056 0.0018165834 0.0000002305]
[0.0519467177 0.0018158954 0.0000002302]
[0.0519369373 0.001815208  0.00000023  ]
[0.0519271641 0.0018145212 0.0000002297]
[0.0519173984 0.0018138352 0.0000002294]
[0.05190764   0.0018131497 0.0000002292]
[0.0518978889 0.0018124649 0.0000002289]
[0.0518881452 0.0018117808 0.0000002286]
[0.0518784088 0.0018110973 0.0000002284]
[0.0518686797 0.0018104145 0.0000002281]
[0.0518589579 0.0018097322 0.0000002278]
[0.0518492434 0.0018090507 0.0000002276]
[0.0518395362 0.0018083697 0.0000002273]
[0.0518298363 0.

[0.0489375981 0.0016106238 0.0000001593]
[0.0489298963 0.0016101144 0.0000001592]
[0.0489221994 0.0016096054 0.000000159 ]
[0.0489145073 0.0016090967 0.0000001589]
[0.04890682   0.0016085885 0.0000001587]
[0.0488991376 0.0016080807 0.0000001585]
[0.04889146   0.0016075733 0.0000001584]
[0.0488837872 0.0016070663 0.0000001582]
[0.0488761193 0.0016065597 0.0000001581]
[0.0488684562 0.0016060535 0.0000001579]
[0.0488607978 0.0016055477 0.0000001578]
[0.0488531443 0.0016050423 0.0000001576]
[0.0488454956 0.0016045373 0.0000001575]
[0.0488378517 0.0016040326 0.0000001573]
[0.0488302126 0.0016035284 0.0000001572]
[0.0488225782 0.0016030246 0.000000157 ]
[0.0488149486 0.0016025212 0.0000001569]
[0.0488073238 0.0016020181 0.0000001567]
[0.0487997038 0.0016015155 0.0000001566]
[0.0487920885 0.0016010132 0.0000001564]
[0.048784478  0.0016005114 0.0000001563]
[0.0487768723 0.0016000099 0.0000001561]
[0.0487692713 0.0015995089 0.000000156 ]
[0.048761675  0.0015990082 0.0000001558]
[0.0487540835 0.

[0.046758977  0.0014697726 0.0000001204]
[0.0467525591 0.0014693673 0.0000001203]
[0.0467461447 0.0014689622 0.0000001202]
[0.0467397339 0.0014685575 0.0000001201]
[0.0467333265 0.001468153  0.00000012  ]
[0.0467269227 0.0014677488 0.0000001199]
[0.0467205224 0.0014673449 0.0000001198]
[0.0467141256 0.0014669413 0.0000001197]
[0.0467077323 0.0014665379 0.0000001196]
[0.0467013425 0.0014661348 0.0000001195]
[0.0466949562 0.001465732  0.0000001194]
[0.0466885734 0.0014653295 0.0000001193]
[0.0466821941 0.0014649273 0.0000001192]
[0.0466758183 0.0014645253 0.0000001191]
[0.046669446  0.0014641236 0.000000119 ]
[0.0466630771 0.0014637222 0.0000001189]
[0.0466567118 0.001463321  0.0000001188]
[0.0466503499 0.0014629201 0.0000001187]
[0.0466439915 0.0014625195 0.0000001186]
[0.0466376365 0.0014621192 0.0000001185]
[0.046631285  0.0014617191 0.0000001184]
[0.046624937  0.0014613194 0.0000001183]
[0.0466185925 0.0014609199 0.0000001182]
[0.0466122514 0.0014605206 0.0000001181]
[0.0466059137 0.

[0.0452562279 0.0013764119 0.0000000985]
[0.0452505969 0.0013760679 0.0000000984]
[0.0452449688 0.0013757241 0.0000000984]
[0.0452393434 0.0013753805 0.0000000983]
[0.0452337209 0.0013750371 0.0000000982]
[0.0452281011 0.001374694  0.0000000981]
[0.0452224842 0.001374351  0.0000000981]
[0.04521687   0.0013740083 0.000000098 ]
[0.0452112587 0.0013736658 0.0000000979]
[0.0452056501 0.0013733235 0.0000000978]
[0.0452000443 0.0013729814 0.0000000978]
[0.0451944413 0.0013726395 0.0000000977]
[0.0451888411 0.0013722978 0.0000000976]
[0.0451832436 0.0013719564 0.0000000975]
[0.045177649  0.0013716152 0.0000000975]
[0.0451720571 0.0013712741 0.0000000974]
[0.0451664679 0.0013709333 0.0000000973]
[0.0451608816 0.0013705927 0.0000000973]
[0.045155298  0.0013702523 0.0000000972]
[0.0451497172 0.0013699122 0.0000000971]
[0.0451441391 0.0013695722 0.000000097 ]
[0.0451385638 0.0013692324 0.000000097 ]
[0.0451329912 0.0013688929 0.0000000969]
[0.0451274214 0.0013685535 0.0000000968]
[0.0451218544 0.

[0.0437170539 0.0012839949 0.0000000797]
[0.0437121515 0.0012837057 0.0000000796]
[0.0437072514 0.0012834167 0.0000000796]
[0.0437023535 0.0012831279 0.0000000795]
[0.0436974578 0.0012828392 0.0000000795]
[0.0436925643 0.0012825507 0.0000000794]
[0.043687673  0.0012822623 0.0000000794]
[0.0436827838 0.0012819741 0.0000000793]
[0.0436778969 0.0012816861 0.0000000793]
[0.0436730122 0.0012813982 0.0000000792]
[0.0436681296 0.0012811105 0.0000000791]
[0.0436632492 0.001280823  0.0000000791]
[0.043658371  0.0012805356 0.000000079 ]
[0.043653495  0.0012802483 0.000000079 ]
[0.0436486212 0.0012799613 0.0000000789]
[0.0436437495 0.0012796744 0.0000000789]
[0.0436388801 0.0012793876 0.0000000788]
[0.0436340128 0.001279101  0.0000000788]
[0.0436291476 0.0012788146 0.0000000787]
[0.0436242847 0.0012785283 0.0000000787]
[0.0436194239 0.0012782422 0.0000000786]
[0.0436145653 0.0012779563 0.0000000786]
[0.0436097089 0.0012776705 0.0000000785]
[0.0436048546 0.0012773849 0.0000000784]
[0.0436000025 0.

[0.0412844026 0.0011445386 0.0000000561]
[0.0412805048 0.0011443216 0.0000000561]
[0.0412766084 0.0011441048 0.0000000561]
[0.0412727135 0.001143888  0.0000000561]
[0.0412688201 0.0011436714 0.000000056 ]
[0.0412649282 0.0011434548 0.000000056 ]
[0.0412610377 0.0011432384 0.000000056 ]
[0.0412571488 0.001143022  0.0000000559]
[0.0412532612 0.0011428058 0.0000000559]
[0.0412493752 0.0011425896 0.0000000559]
[0.0412454906 0.0011423736 0.0000000558]
[0.0412416075 0.0011421577 0.0000000558]
[0.0412377258 0.0011419418 0.0000000558]
[0.0412338456 0.0011417261 0.0000000557]
[0.0412299669 0.0011415105 0.0000000557]
[0.0412260896 0.0011412949 0.0000000557]
[0.0412222138 0.0011410795 0.0000000556]
[0.0412183394 0.0011408642 0.0000000556]
[0.0412144665 0.001140649  0.0000000556]
[0.0412105951 0.0011404338 0.0000000555]
[0.0412067251 0.0011402188 0.0000000555]
[0.0412028565 0.0011400039 0.0000000555]
[0.0411989895 0.0011397891 0.0000000554]
[0.0411951238 0.0011395743 0.0000000554]
[0.0411912597 0.

[0.0398638788 0.0010668426 0.0000000453]
[0.039860491  0.0010666606 0.0000000453]
[0.0398571043 0.0010664787 0.0000000453]
[0.0398537188 0.0010662968 0.0000000453]
[0.0398503344 0.0010661151 0.0000000452]
[0.0398469512 0.0010659334 0.0000000452]
[0.0398435691 0.0010657517 0.0000000452]
[0.0398401882 0.0010655702 0.0000000452]
[0.0398368084 0.0010653887 0.0000000452]
[0.0398334298 0.0010652073 0.0000000451]
[0.0398300523 0.001065026  0.0000000451]
[0.039826676  0.0010648448 0.0000000451]
[0.0398233008 0.0010646636 0.0000000451]
[0.0398199267 0.0010644826 0.000000045 ]
[0.0398165538 0.0010643016 0.000000045 ]
[0.0398131821 0.0010641206 0.000000045 ]
[0.0398098114 0.0010639398 0.000000045 ]
[0.039806442  0.001063759  0.0000000449]
[0.0398030736 0.0010635783 0.0000000449]
[0.0397997065 0.0010633977 0.0000000449]
[0.0397963404 0.0010632172 0.0000000449]
[0.0397929755 0.0010630367 0.0000000449]
[0.0397896117 0.0010628563 0.0000000448]
[0.0397862491 0.001062676  0.0000000448]
[0.0397828876 0.

[0.0383559308 0.0009873769 0.0000000358]
[0.0383530277 0.0009872269 0.0000000358]
[0.0383501256 0.000987077  0.0000000358]
[0.0383472243 0.0009869271 0.0000000358]
[0.0383443239 0.0009867773 0.0000000358]
[0.0383414243 0.0009866275 0.0000000358]
[0.0383385257 0.0009864778 0.0000000357]
[0.0383356279 0.0009863281 0.0000000357]
[0.038332731  0.0009861785 0.0000000357]
[0.038329835  0.000986029  0.0000000357]
[0.0383269399 0.0009858795 0.0000000357]
[0.0383240456 0.0009857301 0.0000000357]
[0.0383211522 0.0009855807 0.0000000356]
[0.0383182597 0.0009854314 0.0000000356]
[0.0383153681 0.0009852822 0.0000000356]
[0.0383124773 0.000985133  0.0000000356]
[0.0383095874 0.0009849838 0.0000000356]
[0.0383066984 0.0009848347 0.0000000356]
[0.0383038103 0.0009846857 0.0000000355]
[0.038300923  0.0009845367 0.0000000355]
[0.0382980366 0.0009843878 0.0000000355]
[0.0382951511 0.0009842389 0.0000000355]
[0.0382922664 0.0009840901 0.0000000355]
[0.0382893826 0.0009839414 0.0000000355]
[0.0382864997 0.

[0.0374562731 0.0009414428 0.000000031 ]
[0.0374536333 0.0009413097 0.000000031 ]
[0.0374509942 0.0009411766 0.000000031 ]
[0.0374483559 0.0009410435 0.000000031 ]
[0.0374457183 0.0009409105 0.000000031 ]
[0.0374430815 0.0009407775 0.0000000309]
[0.0374404454 0.0009406446 0.0000000309]
[0.0374378101 0.0009405117 0.0000000309]
[0.0374351755 0.0009403789 0.0000000309]
[0.0374325416 0.0009402461 0.0000000309]
[0.0374299085 0.0009401134 0.0000000309]
[0.0374272762 0.0009399807 0.0000000309]
[0.0374246445 0.000939848  0.0000000309]
[0.0374220137 0.0009397154 0.0000000308]
[0.0374193835 0.0009395829 0.0000000308]
[0.0374167541 0.0009394504 0.0000000308]
[0.0374141254 0.0009393179 0.0000000308]
[0.0374114975 0.0009391855 0.0000000308]
[0.0374088703 0.0009390532 0.0000000308]
[0.0374062439 0.0009389208 0.0000000308]
[0.0374036182 0.0009387886 0.0000000308]
[0.0374009932 0.0009386563 0.0000000307]
[0.037398369  0.0009385242 0.0000000307]
[0.0373957455 0.000938392  0.0000000307]
[0.0373931227 0.

[0.0363081291 0.0008844226 0.0000000257]
[0.0363057987 0.0008843087 0.0000000257]
[0.036303469  0.0008841948 0.0000000256]
[0.0363011398 0.000884081  0.0000000256]
[0.0362988112 0.0008839672 0.0000000256]
[0.0362964833 0.0008838534 0.0000000256]
[0.0362941559 0.0008837397 0.0000000256]
[0.0362918291 0.000883626  0.0000000256]
[0.0362895029 0.0008835123 0.0000000256]
[0.0362871773 0.0008833987 0.0000000256]
[0.0362848524 0.0008832851 0.0000000256]
[0.036282528  0.0008831716 0.0000000256]
[0.0362802042 0.0008830581 0.0000000255]
[0.036277881  0.0008829446 0.0000000255]
[0.0362755584 0.0008828312 0.0000000255]
[0.0362732364 0.0008827178 0.0000000255]
[0.036270915  0.0008826044 0.0000000255]
[0.0362685942 0.0008824911 0.0000000255]
[0.0362662739 0.0008823778 0.0000000255]
[0.0362639543 0.0008822646 0.0000000255]
[0.0362616353 0.0008821514 0.0000000255]
[0.0362593168 0.0008820382 0.0000000255]
[0.036256999  0.000881925  0.0000000254]
[0.0362546818 0.0008818119 0.0000000254]
[0.0362523651 0.

[0.0353958025 0.0008403928 0.000000022 ]
[0.035393698  0.0008402925 0.000000022 ]
[0.0353915939 0.0008401923 0.000000022 ]
[0.0353894903 0.0008400921 0.000000022 ]
[0.0353873873 0.0008399919 0.0000000219]
[0.0353852847 0.0008398918 0.0000000219]
[0.0353831826 0.0008397917 0.0000000219]
[0.0353810811 0.0008396916 0.0000000219]
[0.03537898   0.0008395915 0.0000000219]
[0.0353768794 0.0008394915 0.0000000219]
[0.0353747794 0.0008393915 0.0000000219]
[0.0353726798 0.0008392915 0.0000000219]
[0.0353705807 0.0008391916 0.0000000219]
[0.0353684822 0.0008390917 0.0000000219]
[0.0353663841 0.0008389918 0.0000000219]
[0.0353642865 0.000838892  0.0000000219]
[0.0353621895 0.0008387922 0.0000000219]
[0.0353600929 0.0008386924 0.0000000218]
[0.0353579968 0.0008385926 0.0000000218]
[0.0353559012 0.0008384929 0.0000000218]
[0.0353538061 0.0008383932 0.0000000218]
[0.0353517115 0.0008382936 0.0000000218]
[0.0353496175 0.0008381939 0.0000000218]
[0.0353475239 0.0008380943 0.0000000218]
[0.0353454308 0.

[0.0348214262 0.0008132534 0.0000000199]
[0.0348194551 0.0008131611 0.0000000199]
[0.0348174845 0.0008130687 0.0000000199]
[0.0348155143 0.0008129764 0.0000000199]
[0.0348135445 0.0008128842 0.0000000199]
[0.0348115752 0.0008127919 0.0000000199]
[0.0348096063 0.0008126997 0.0000000199]
[0.0348076379 0.0008126075 0.0000000199]
[0.0348056699 0.0008125153 0.0000000198]
[0.0348037024 0.0008124231 0.0000000198]
[0.0348017353 0.000812331  0.0000000198]
[0.0347997687 0.0008122389 0.0000000198]
[0.0347978025 0.0008121468 0.0000000198]
[0.0347958367 0.0008120548 0.0000000198]
[0.0347938714 0.0008119628 0.0000000198]
[0.0347919065 0.0008118708 0.0000000198]
[0.0347899421 0.0008117788 0.0000000198]
[0.0347879782 0.0008116868 0.0000000198]
[0.0347860146 0.0008115949 0.0000000198]
[0.0347840515 0.000811503  0.0000000198]
[0.0347820889 0.0008114112 0.0000000198]
[0.0347801267 0.0008113193 0.0000000198]
[0.0347781649 0.0008112275 0.0000000198]
[0.0347762036 0.0008111357 0.0000000197]
[0.0347742428 0.

[0.0341759022 0.0007832876 0.0000000178]
[0.0341740734 0.0007832035 0.0000000178]
[0.034172245  0.0007831195 0.0000000178]
[0.034170417  0.0007830354 0.0000000177]
[0.0341685893 0.0007829514 0.0000000177]
[0.0341667621 0.0007828674 0.0000000177]
[0.0341649353 0.0007827834 0.0000000177]
[0.0341631088 0.0007826995 0.0000000177]
[0.0341612828 0.0007826155 0.0000000177]
[0.0341594571 0.0007825316 0.0000000177]
[0.0341576319 0.0007824477 0.0000000177]
[0.034155807  0.0007823639 0.0000000177]
[0.0341539825 0.00078228   0.0000000177]
[0.0341521584 0.0007821962 0.0000000177]
[0.0341503347 0.0007821124 0.0000000177]
[0.0341485114 0.0007820286 0.0000000177]
[0.0341466884 0.0007819449 0.0000000177]
[0.0341448659 0.0007818612 0.0000000177]
[0.0341430437 0.0007817775 0.0000000177]
[0.034141222  0.0007816938 0.0000000177]
[0.0341394006 0.0007816101 0.0000000176]
[0.0341375796 0.0007815265 0.0000000176]
[0.034135759  0.0007814428 0.0000000176]
[0.0341339388 0.0007813592 0.0000000176]
[0.034132119  0.

[0.0337097361 0.0007619999 0.0000000163]
[0.0337080051 0.0007619214 0.0000000163]
[0.0337062746 0.0007618429 0.0000000163]
[0.0337045443 0.0007617644 0.0000000163]
[0.0337028145 0.000761686  0.0000000163]
[0.033701085  0.0007616076 0.0000000163]
[0.0336993558 0.0007615292 0.0000000163]
[0.033697627  0.0007614508 0.0000000163]
[0.0336958986 0.0007613725 0.0000000163]
[0.0336941705 0.0007612941 0.0000000163]
[0.0336924428 0.0007612158 0.0000000163]
[0.0336907154 0.0007611375 0.0000000163]
[0.0336889884 0.0007610593 0.0000000163]
[0.0336872618 0.000760981  0.0000000163]
[0.0336855354 0.0007609028 0.0000000163]
[0.0336838095 0.0007608246 0.0000000163]
[0.0336820839 0.0007607464 0.0000000163]
[0.0336803587 0.0007606682 0.0000000163]
[0.0336786338 0.0007605901 0.0000000162]
[0.0336769092 0.0007605119 0.0000000162]
[0.033675185  0.0007604338 0.0000000162]
[0.0336734612 0.0007603557 0.0000000162]
[0.0336717377 0.0007602777 0.0000000162]
[0.0336700146 0.0007601996 0.0000000162]
[0.0336682918 0.

[0.032791094  0.0007209135 0.0000000138]
[0.0327895444 0.0007208451 0.0000000138]
[0.0327879951 0.0007207768 0.0000000138]
[0.032786446  0.0007207085 0.0000000138]
[0.0327848973 0.0007206402 0.0000000138]
[0.0327833489 0.0007205719 0.0000000138]
[0.0327818007 0.0007205037 0.0000000138]
[0.0327802528 0.0007204354 0.0000000138]
[0.0327787053 0.0007203672 0.0000000138]
[0.032777158  0.000720299  0.0000000138]
[0.032775611  0.0007202308 0.0000000138]
[0.0327740643 0.0007201626 0.0000000138]
[0.0327725179 0.0007200945 0.0000000138]
[0.0327709718 0.0007200263 0.0000000138]
[0.032769426  0.0007199582 0.0000000138]
[0.0327678805 0.0007198901 0.0000000138]
[0.0327663352 0.000719822  0.0000000138]
[0.0327647903 0.0007197539 0.0000000137]
[0.0327632457 0.0007196858 0.0000000137]
[0.0327617013 0.0007196178 0.0000000137]
[0.0327601572 0.0007195498 0.0000000137]
[0.0327586135 0.0007194817 0.0000000137]
[0.03275707   0.0007194137 0.0000000137]
[0.0327555268 0.0007193458 0.0000000137]
[0.0327539839 0.

[0.0321248523 0.0006918325 0.0000000122]
[0.0321234249 0.0006917708 0.0000000122]
[0.0321219979 0.0006917092 0.0000000122]
[0.032120571  0.0006916476 0.0000000122]
[0.0321191445 0.0006915859 0.0000000122]
[0.0321177182 0.0006915243 0.0000000122]
[0.0321162921 0.0006914628 0.0000000122]
[0.0321148663 0.0006914012 0.0000000122]
[0.0321134407 0.0006913396 0.0000000122]
[0.0321120154 0.0006912781 0.0000000122]
[0.0321105904 0.0006912165 0.0000000122]
[0.0321091656 0.000691155  0.0000000122]
[0.032107741  0.0006910935 0.0000000122]
[0.0321063167 0.000691032  0.0000000122]
[0.0321048927 0.0006909706 0.0000000122]
[0.0321034689 0.0006909091 0.0000000121]
[0.0321020454 0.0006908476 0.0000000121]
[0.0321006221 0.0006907862 0.0000000121]
[0.0320991991 0.0006907248 0.0000000121]
[0.0320977763 0.0006906634 0.0000000121]
[0.0320963538 0.000690602  0.0000000121]
[0.0320949315 0.0006905406 0.0000000121]
[0.0320935095 0.0006904792 0.0000000121]
[0.0320920877 0.0006904179 0.0000000121]
[0.0320906662 0.

[0.0315388299 0.000666751  0.0000000109]
[0.031537504  0.0006666947 0.0000000109]
[0.0315361784 0.0006666385 0.0000000109]
[0.0315348529 0.0006665823 0.0000000109]
[0.0315335277 0.0006665261 0.0000000109]
[0.0315322027 0.00066647   0.0000000109]
[0.0315308779 0.0006664138 0.0000000109]
[0.0315295534 0.0006663577 0.0000000109]
[0.0315282291 0.0006663015 0.0000000109]
[0.031526905  0.0006662454 0.0000000109]
[0.0315255811 0.0006661893 0.0000000109]
[0.0315242574 0.0006661332 0.0000000109]
[0.031522934  0.0006660771 0.0000000109]
[0.0315216108 0.000666021  0.0000000109]
[0.0315202878 0.000665965  0.0000000109]
[0.031518965  0.0006659089 0.0000000109]
[0.0315176424 0.0006658529 0.0000000109]
[0.0315163201 0.0006657968 0.0000000109]
[0.031514998  0.0006657408 0.0000000109]
[0.0315136761 0.0006656848 0.0000000109]
[0.0315123545 0.0006656288 0.0000000109]
[0.031511033  0.0006655728 0.0000000109]
[0.0315097118 0.0006655169 0.0000000108]
[0.0315083908 0.0006654609 0.0000000108]
[0.0315070701 0.